FROM java:8
MAINTAINER ljc
EXPOSE 8075
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo "Asia/Shanghai" > /etc/timezone
RUN mkdir -p /opt/apps/
WORKDIR /opt/oa/
# ADD   codework-application.jar .
RUN bash -c "touch /opt/apps/codework-application.jar"
ENTRYPOINT ["java","-jar","/opt/apps/codework-application.jar"]

